#!/bin/sh

cd ~/.vim
echo "Fetching plugins"
git submodule init
git submodule update
echo "Setting up symlinks"
ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc
ln -s ~/.vim/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim
